services:
  twinkleshine:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./.env:/app/.env
